pipeline {
  agent any

  tools {
    nodejs 'NodeJS 18'   
  }

  environment {
    IMAGE_NAME = "user-service"
    DOCKERHUB_REPO = "hannanahmed/user-service"
  }

  stages {

    stage('Checkout Code') {
      steps {
        git 'https://github.com/HannanDevops28/nodejs_microservices.git' 
      }
    }

    stage('Install Dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Test') {
      steps {
        echo "✅ Test skipped (add later)"
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $IMAGE_NAME .'
      }
    }

    stage('Push to DockerHub') {
      steps {
        withDockerRegistry([credentialsId: 'dockerhub-credentials-id', url: '']) {
          sh 'docker tag $IMAGE_NAME $DOCKERHUB_REPO:latest'
          sh 'docker push $DOCKERHUB_REPO:latest'
        }
      }
    }

  }

  post {
    success {
      echo "🎉 Build and Push successful!"
    }
    failure {
      echo "❌ Build failed"
    }
  }
}
