version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    env_file:
      - ./order-service/.env
    depends_on:
      - mongo
