version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_bash:/var/jenkins_bash
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_bash:
