- hosts: ec2
  become: true
  vars:
    region: "{{ region }}"
    image_name: "{{ image_name }}"
    ecr_repo_url: "{{ ecr_repo_url }}"  # e.g., 781860574009.dkr.ecr.ap-south-1.amazonaws.com/my-app
    ecr_registry: "{{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com"
    container_port: 3000
    host_port: 3000

  tasks:

    - name: Install AWS CLI and Docker
      package:
        name:
          - awscli
          - docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Login to AWS ECR
      shell: >
        aws ecr get-login-password --region {{ region }} |
        docker login --username AWS --password-stdin {{ ecr_registry }}
      register: ecr_login
      changed_when: false
      failed_when: "'Login Succeeded' not in ecr_login.stdout"

    - name: Pull Docker image from ECR
      shell: docker pull {{ ecr_repo_url }}:latest
      register: docker_pull
      changed_when: "'Downloaded newer image' in docker_pull.stdout"

    - name: Stop existing container if running
      shell: docker stop {{ image_name }}
      ignore_errors: true

    - name: Remove existing container if stopped
      shell: docker rm {{ image_name }}
      ignore_errors: true

    - name: Run Docker container
      shell: >
        docker run -d
        -p {{ host_port }}:{{ container_port }}
        --name {{ image_name }}
        {{ ecr_repo_url }}:latest
