- hosts: ec2
  become: true
  vars:
    region: "{{ region }}"
    image_name: "{{ image_name }}"
    ecr_repo_url: "{{ ecr_repo_url }}"
    ecr_registry: "{{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com"
    container_port: 3000
    host_port: 3000

  tasks:

    - name: Install required packages (AWS CLI & Docker)
      package:
        name:
          - awscli
          - docker
        state: present

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Login to AWS ECR
      shell: >
        aws ecr get-login-password --region {{ region }} |
        docker login --username AWS --password-stdin {{ ecr_registry }}
      register: ecr_login
      changed_when: false
      failed_when: ecr_login.rc != 0

    - name: Pull Docker image from ECR
      shell: docker pull {{ ecr_repo_url }}:latest
      register: docker_pull
      changed_when: "'Downloaded newer image' in docker_pull.stdout"

    - name: Stop running container if exists
      shell: docker stop {{ image_name }}
      ignore_errors: true

    - name: Remove stopped container if exists
      shell: docker rm {{ image_name }}
      ignore_errors: true

    - name: Run Docker container from pulled image
      shell: >
        docker run -d
        -p {{ host_port }}:{{ container_port }}
        --name {{ image_name }}
        {{ ecr_repo_url }}:latest
